# Generated by Django 4.1.3 on 2022-11-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.IntegerField(blank=True)),
                ('h', models.IntegerField(blank=True)),
                ('r', models.DecimalField(decimal_places=10, default='', max_digits=10)),
                ('d', models.DecimalField(decimal_places=10, default='', max_digits=10)),
                ('l', models.DecimalField(decimal_places=10, default='', max_digits=10)),
                ('segment_i_node', models.IntegerField(blank=True)),
                ('index', models.IntegerField(blank=True)),
                ('nodes', models.IntegerField(blank=True)),
                ('xpos', models.DecimalField(decimal_places=10, default='', max_digits=10)),
                ('ypos', models.DecimalField(decimal_places=10, default='', max_digits=10)),
                ('zpos', models.DecimalField(decimal_places=10, default='', max_digits=10)),
                ('volume_ratio', models.IntegerField(blank=True)),
                ('hNode', models.IntegerField(blank=True)),
                ('tNode', models.IntegerField(blank=True)),
                ('nodes_mesh', models.IntegerField(blank=True)),
                ('xpos_mesh', models.DecimalField(decimal_places=10, default='', max_digits=10)),
            ],
        ),
    ]
