# Generated by Django 4.1.3 on 2022-12-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectworkapp', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
