# Generated by Django 4.1.3 on 2022-12-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectworkapp', '0003_uploadfile_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.FileField(max_length=254, upload_to=None)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
