# Generated by Django 4.0.4 on 2023-01-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectworkapp', '0005_upload_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFiles',
        ),
        migrations.RenameField(
            model_name='upload_file',
            old_name='foldername',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='upload_file',
            old_name='file',
            new_name='my_file',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='id',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='user',
        ),
        migrations.AddField(
            model_name='upload_file',
            name='ids',
            field=models.AutoField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
