# Generated by Django 4.1.5 on 2023-01-26 19:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectworkapp', '0007_alter_upload_file_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='user',
            field=models.ForeignKey(default=datetime.date, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
