# Generated by Django 4.1.5 on 2023-01-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectworkapp', '0008_upload_file_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dataapp',
        ),
    ]
